#
#	DSAD Deep Security Debug Logs Anonymizer
#	(c) 2024 by Mikhail Kondrashin (mkondrashin@gmail.com)
#
#	build.yml
#
#	build and publish
#

name: BUILD RELEASE
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    - name: Setup Go
      uses: actions/setup-go@v2
    - run: echo "Go installed"
    - name: Check Go version
      run: go version
    - id: get_version
      uses: battila7/get-version-action@v2
    - run: echo ${{ steps.get_version.outputs.version }}
    - name: Run tests
      run: go test -v -race ./...
    - run: echo "Build is finished"
    - name: List files in the repository
      run: |
        ls -R ${{ github.workspace }}
    
    - name: Build DSAD Linux
      run: GOOS=linux GOARCH=amd64 go build
    - name: Pack ACLI Linux
      run: tar cfvz dsad_linux_x64.tgz dsad

    - name: Build DSAD Windows
      run: GOOS=windows GOARCH=amd64 go build
    - name: Pack DSAD Windows
      run: tar cfvz dsad_windows_x64.tgz dsad.exe

    - name: Build DSAD Darwin ARM64
      run: GOOS=darwin GOARCH=arm64 go build
    - name: Pack DSAD Darwin
      run: tar cfvz dsad_darwin_arm64.tgz dsad

    - name: Build DSAD Darwin x64
      run: GOOS=darwin GOARCH=amd64 go build
    - name: Pack DSAD Darwin
      run: tar cfvz dsad_darwin_amd4.tgz dsad

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dsad_linux_x64.tgz
          dsad_windows_x64.tgz
          dsad_darwin_arm64.tgz
          dsad_darwin_amd4.tgz
